alias li='ls -lhF'
alias dbmagic='rake db:drop db:create db:migrate db:seed RAILS_ENV=development'
alias cdrlc='cd ~/Documents/RLC/website'
alias repy='python repy.py restrictions.default encasementlib.r2py'
alias be='bundle exec '
alias RED='RAILS_ENV=development'
alias chrome='/usr/bin/google-chrome'
alias ghc='stack ghc'
alias ghci='stack ghci'
alias e='emacsclient -cna ""'
alias et='emacsclient -ta ""'
